### ISSUE TITLE
Injecting 2 repositories 

### ISSUE THREAD

**Issue by Firman95** [freevital/laravel-repository#3]
If I inject BRepo in ARepo, how to inject ARepo in BRepo?

This is my BRepo
```
class BRepository extends BaseRepository
{
    /**
     * @var ARepository
     */
    private $aRepo;

    /**
     * @param Application $app
     * @param ARepository $aRepo
     */
    public function __construct(Application $app, ARepository $aRepo)
    {
        parent::__construct($app);

        $this->aRepo = $aRepo;
    }
}
```
This is my ARepo
```
class ARepository extends BaseRepository
{
    /**
     * @var BRepository
     */
    private $bRepo;

    /**
     * @param Application $app
     * @param BRepository $bRepo
     */
    public function __construct(Application $app, BRepository $bRepo)
    {
        parent::__construct($app);
        $this->bRepo = $bRepo;
    }
}
```
I get Http Error 500, "domain.com is currently unable to handle this request", for all routing that use ARepository or BRepository class. I can inject ARepository with all other repositories with no problem except for BRepository class. Thanks in advance.

**Comment by freevital** [comment]
That's because ARepository instance depends on BRepository instance which is injected during the instantialization of ARepository. So to create ARepository you have to create first an instance of BRepository. And to create BRepository you have to create ARepository first which is imposible in this case because of the recursion it causes.

**Comment by Firman95** [comment]
@freevital is there another way to use ARepo in BRepo and vice versa?

**Comment by freevital** [comment]
@Firman95 you can use as many of them as you like, but you can't use constructor DI in recursive manner.
